In [ ]:
# importing libraries
import pandas as pd 
import numpy as np

In [ ]:
# Import dependency index dataset
dependency_index_county_2013_2024 = pd.read_excel('dependency_index_county_2013_2024.xlsx')

# Display dataset
dependency_index_county_2013_2024

      County  Years  Dependency index
0       Alba   2013         48.336486
1       Alba   2014         48.533868
2       Alba   2015         49.171577
3       Alba   2016         50.008996
4       Alba   2017         51.266980
..       ...    ...               ...
499  Vrancea   2020         60.226895
500  Vrancea   2021         61.332752
501  Vrancea   2022         58.134757
502  Vrancea   2023         58.401879
503  Vrancea   2024         58.257851

[504 rows x 3 columns]

In [ ]:
# Remove leading spaces from county names
dependency_index_county_2013_2024['County'] = dependency_index_county_2013_2024['County'].str.lstrip(' ')

In [ ]:
# Import enterprises per capita dataset
enterprises_capita_county_2013_2024 = pd.read_excel('enterprises_capita_county_2013_2024.xlsx')

# Display dataset
enterprises_capita_county_2013_2024

      County  Years  Enterprises per capita
0       Alba   2013               21.562985
1       Arad   2013               24.465522
2      Arges   2013               21.987874
3      Bacau   2013               17.340822
4      Bihor   2013               28.337998
..       ...    ...                     ...
499    Timis   2024               49.125678
500   Tulcea   2024               30.564710
501   Valcea   2024               29.136588
502   Vaslui   2024               18.586425
503  Vrancea   2024               25.301448

[504 rows x 3 columns]

In [ ]:
# Remove leading spaces from county names
enterprises_capita_county_2013_2024['County'] = enterprises_capita_county_2013_2024['County'].str.lstrip(' ')

In [ ]:
# Import FDI per capita dataset
fdi_capita_county_2013_2024 = pd.read_excel('fdi_capita_county_2013_2024.xlsx')

# Display dataset
fdi_capita_county_2013_2024

        County  Years  FDI per capita
0         Alba   2013        2.609590
1        Arges   2013        2.389628
2         Arad   2013        1.768985
3        Bacau   2013        0.270515
4        Bihor   2013        0.914353
..         ...    ...             ...
499      Timis   2024        8.646011
500  Teleorman   2024        0.339164
501     Valcea   2024        0.569521
502    Vrancea   2024        0.321986
503     Vaslui   2024        0.121781

[504 rows x 3 columns]

In [ ]:
# Remove leading spaces from county names
fdi_capita_county_2013_2024['County'] = fdi_capita_county_2013_2024['County'].str.lstrip(' ')

In [ ]:
# Import occupancy rate dataset
occupancy_rate_county_2013_2024 = pd.read_excel('occupancy_rate_county_2013_2024.xlsx')

# Display dataset
occupancy_rate_county_2013_2024

      County  Years  Occupancy rate
0       Alba   2013       71.346496
1       Alba   2014       70.194883
2       Alba   2015       70.696799
3       Alba   2016       71.925942
4       Alba   2017       74.089987
..       ...    ...             ...
499  Vrancea   2020       65.900267
500  Vrancea   2021       55.403083
501  Vrancea   2022       52.496047
502  Vrancea   2023       51.920389
503  Vrancea   2024       50.956749

[504 rows x 3 columns]

In [ ]:
# Remove leading spaces from county names
occupancy_rate_county_2013_2024['County'] = occupancy_rate_county_2013_2024['County'].str.lstrip(' ')

In [ ]:
# Import real salary dataset
real_salary_county_2013_2024 = pd.read_excel('real_salary_county_2013_2024.xlsx')

# Display dataset
real_salary_county_2013_2024

    County  Years  Real salary
0    Bihor   2013         1799
1    Bihor   2014         2002
2    Bihor   2015         2164
3    Bihor   2016         2461
4    Bihor   2017         2907
..     ...    ...          ...
499  Timis   2020         4928
500  Timis   2021         5101
501  Timis   2022         4955
502  Timis   2023         5184
503  Timis   2024         5508

[504 rows x 3 columns]

In [ ]:
# Remove leading spaces from county names
real_salary_county_2013_2024['County'] = real_salary_county_2013_2024['County'].str.lstrip(' ')

In [ ]:
# Import temporary immigrants dataset
temporary_immigrants_county_2013_2024 = pd.read_excel('temporary_immigrants_county_2013_2024.xlsx')

# Display dataset
temporary_immigrants_county_2013_2024

     County  Years  Immigrants
0     Bihor   2013        4403
1     Bihor   2014        3898
2     Bihor   2015        3805
3     Bihor   2016        3939
4     Bihor   2017        5085
..      ...    ...         ...
499   Timis   2020        5215
500   Timis   2021        6975
501   Timis   2022       10501
502   Timis   2023       11117
503   Timis   2024        9829

[504 rows x 3 columns]

In [ ]:
# Remove leading spaces from county names
temporary_immigrants_county_2013_2024['County'] = temporary_immigrants_county_2013_2024['County'].str.lstrip(' ')

In [ ]:
# Merge dependency index and enterprises datasets
df_panel = pd.merge(
    dependency_index_county_2013_2024,
    enterprises_capita_county_2013_2024,
    how = 'inner',
    on = ['County', 'Years']
)

# Merge FDI dataset
df_panel = pd.merge(
    df_panel,
    fdi_capita_county_2013_2024,
    how = 'inner',
    on = ['County', 'Years']
)

# Merge occupancy rate dataset
df_panel = pd.merge(
    df_panel,
    occupancy_rate_county_2013_2024,
    how = 'inner',
    on = ['County', 'Years']
)

# Merge real salary dataset
df_panel = pd.merge(
    df_panel,
    real_salary_county_2013_2024,
    how = 'inner',
    on = ['County', 'Years']
)

# Merge temporary immigrants dataset
df_panel = pd.merge(
    df_panel,
    temporary_immigrants_county_2013_2024,
    how = 'inner',
    on = ['County', 'Years']
)

# Display final panel dataset
df_panel

,County,Years,Dependency index,Enterprises per capita,FDI per capita,Occupancy rate,Real salary,Immigrants
0,Alba,2013,48.336486,21.562985,2.609590,71.346496,2061,2714
1,Alba,2014,48.533868,22.394490,3.529582,70.194883,2208,2403
2,Alba,2015,49.171577,23.011774,2.866797,70.696799,2462,2346
3,Alba,2016,50.008996,23.757976,3.307465,71.925942,2782,2428
4,Alba,2017,51.266980,24.659016,2.501858,74.089987,3196,3134
...,...,...,...,...,...,...,...,...
499,Vrancea,2020,60.226895,23.698934,0.377622,65.900267,3569,2412
500,Vrancea,2021,61.332752,25.281881,0.362487,55.403083,3513,3226
501,Vrancea,2022,58.134757,24.174864,0.356217,52.496047,3367,4857
502,Vrancea,2023,58.401879,25.201558,0.372200,51.920389,3531,5694
503,Vrancea,2024,58.257851,25.301448,0.321986,50.956749,3890,5034

In [ ]:
# Export panel dataset to Excel
df_panel.to_excel('panel_data.xlsx', index = False)