In [2]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

## Processing total number of temporary immigrants

In [3]:
# Import the CSV file containing temporary immigration data
# Rename the columns of the dataset
# Skip the first row from the file (original header)
# Display the resulting DataFrame
df_temporary_imigrants_total = pd.read_csv('Data/Temporary imigration/exportPivot_POP321A.csv', names = ['Age', 'Sex', 'Years', 'Persons', 'Immigrants'], skiprows = 1)

# Display the resulting DataFrame
df_temporary_imigrants_total

      Age     Sex       Years             Persons  Immigrants
0   Total   Total   Year 2013   Number of persons      153646
1   Total   Total   Year 2014   Number of persons      136035
2   Total   Total   Year 2015   Number of persons      132795
3   Total   Total   Year 2016   Number of persons      137455
4   Total   Total   Year 2017   Number of persons      177435
5   Total   Total   Year 2018   Number of persons      172578
6   Total   Total   Year 2019   Number of persons      202422
7   Total   Total   Year 2020   Number of persons      145519
8   Total   Total   Year 2021   Number of persons      194642
9   Total   Total   Year 2022   Number of persons      293024
10  Total   Total   Year 2023   Number of persons      324091
11  Total   Total   Year 2024   Number of persons      286538

In [4]:
# Remove unnecessary columns from the DataFrame
df_temporary_imigrants_total = df_temporary_imigrants_total.drop(['Age', 'Sex', 'Persons'], axis = 1)

# Display the updated DataFrame
df_temporary_imigrants_total

         Years  Immigrants
0    Year 2013      153646
1    Year 2014      136035
2    Year 2015      132795
3    Year 2016      137455
4    Year 2017      177435
5    Year 2018      172578
6    Year 2019      202422
7    Year 2020      145519
8    Year 2021      194642
9    Year 2022      293024
10   Year 2023      324091
11   Year 2024      286538

In [5]:
# Remove the 'Year' prefix from the values in the 'Years' column
df_temporary_imigrants_total['Years'] = df_temporary_imigrants_total['Years'].str.lstrip(' Year')

# Display the updated DataFrame
df_temporary_imigrants_total

   Years  Immigrants
0   2013      153646
1   2014      136035
2   2015      132795
3   2016      137455
4   2017      177435
5   2018      172578
6   2019      202422
7   2020      145519
8   2021      194642
9   2022      293024
10  2023      324091
11  2024      286538

In [6]:
# Export the DataFrame to an Excel file and keep the index as 'Years'
df_temporary_imigrants_total.to_excel('temporary_immigrants_total_2013_2024.xlsx', index = False)

## Processing number of temporary immigrants by county

In [10]:
# Import the CSV file containing temporary immigration data by county
# Rename the columns of the dataset
# Skip the first row from the file (original header)
df_temporary_imigrants_county = pd.read_csv('Data/Temporary imigration/exportPivot_POP321C.csv', names = ['Age', 'Sex', 'Areas', 'County', 'Years', 'Persons', 'Immigrants'], skiprows = 1)

# Display the resulting DataFrame
df_temporary_imigrants_county

       Age     Sex   Areas  County       Years             Persons  Immigrants
0    Total   Total   Total   Bihor   Year 2013   Number of persons        4403
1    Total   Total   Total   Bihor   Year 2014   Number of persons        3898
2    Total   Total   Total   Bihor   Year 2015   Number of persons        3805
3    Total   Total   Total   Bihor   Year 2016   Number of persons        3939
4    Total   Total   Total   Bihor   Year 2017   Number of persons        5085
..     ...     ...     ...     ...         ...                 ...         ...
499  Total   Total   Total   Timis   Year 2020   Number of persons        5215
500  Total   Total   Total   Timis   Year 2021   Number of persons        6975
501  Total   Total   Total   Timis   Year 2022   Number of persons       10501
502  Total   Total   Total   Timis   Year 2023   Number of persons       11117
503  Total   Total   Total   Timis   Year 2024   Number of persons        9829

[504 rows x 7 columns]

In [11]:
# Remove unnecessary columns from the DataFrame
df_temporary_imigrants_county = df_temporary_imigrants_county.drop(['Age', 'Sex', 'Areas', 'Persons'], axis = 1)

# Display the cleaned DataFrame
df_temporary_imigrants_county

     County       Years  Immigrants
0     Bihor   Year 2013        4403
1     Bihor   Year 2014        3898
2     Bihor   Year 2015        3805
3     Bihor   Year 2016        3939
4     Bihor   Year 2017        5085
..      ...         ...         ...
499   Timis   Year 2020        5215
500   Timis   Year 2021        6975
501   Timis   Year 2022       10501
502   Timis   Year 2023       11117
503   Timis   Year 2024        9829

[504 rows x 3 columns]

In [12]:
# Remove the 'Year' prefix from the values in the 'Years' column
df_temporary_imigrants_county['Years'] = df_temporary_imigrants_county['Years'].str.lstrip(' Year')

# Display the updated DataFrame
df_temporary_imigrants_county

     County Years  Immigrants
0     Bihor  2013        4403
1     Bihor  2014        3898
2     Bihor  2015        3805
3     Bihor  2016        3939
4     Bihor  2017        5085
..      ...   ...         ...
499   Timis  2020        5215
500   Timis  2021        6975
501   Timis  2022       10501
502   Timis  2023       11117
503   Timis  2024        9829

[504 rows x 3 columns]

In [ ]:
# Export the DataFrame to an Excel file without including the index
df_temporary_imigrants_county.to_excel('temporary_immigrants_county_2013_2024.xlsx', index = False)

## FDI Processing

In [ ]:
# Import the Excel file containing FDI data
df_fdi = pd.read_excel('Data/FDI/FDI.xlsx')

# Display the first rows of the DataFrame
df_fdi.head()

,County,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Alba,886,1192,963,1103,828,828,1065,1024,1270.0,1327.0,1375.0,1580.0
1,Arges,1450,582,791,1037,1117,1233,1425,1521,1606.0,1743.0,1850.0,1962.0
2,Arad,760,854,959,1079,1216,1011,914,1103,1498.0,1362.0,1582.0,1739.0
3,Bacau,165,165,193,143,144,458,356,329,NaN,NaN,1257.0,979.0
4,Bihor,526,584,613,656,667,700,876,1023,1014.0,1082.0,1293.0,1798.0

In [ ]:
# Display information about the DataFrame structure and data types
df_fdi.info()

<class 'pandas.DataFrame'>
RangeIndex: 42 entries, 0 to 41
Data columns (total 13 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   County  42 non-null     str
 1   2013    42 non-null     int64
 2   2014    42 non-null     int64
 3   2015    42 non-null     int64
 4   2016    42 non-null     int64
 5   2017    42 non-null     int64
 6   2018    42 non-null     int64
 7   2019    42 non-null     int64
 8   2020    42 non-null     int64
 9   2021    40 non-null     float64
 10  2022    40 non-null     float64
 11  2023    40 non-null     float64
 12  2024    40 non-null     float64
dtypes: float64(4), int64(8), str(1)
memory usage: 4.7 KB

In [27]:
# Check the number of missing values in each column
df_fdi.isnull().sum()

County    0
2013      0
2014      0
2015      0
2016      0
2017      0
2018      0
2019      0
2020      0
2021      2
2022      2
2023      2
2024      2
dtype: int64

In [28]:
# Display the column names of the DataFrame
df_fdi.columns

Index(['County',     2013,     2014,     2015,     2016,     2017,     2018,
           2019,     2020,     2021,     2022,     2023,     2024],
      dtype='object')

In [ ]:
# Convert all column names to string type
df_fdi.columns = df_fdi.columns.astype(str)

# Display the updated column names
df_fdi.columns

# Display the updated DataFrame
df_fdi

,County,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Alba,886,1192,963,1103,828,828,1065,1024,1270.0,1327.0,1375.0,1580.0
1,Arges,1450,582,791,1037,1117,1233,1425,1521,1606.0,1743.0,1850.0,1962.0
2,Arad,760,854,959,1079,1216,1011,914,1103,1498.0,1362.0,1582.0,1739.0
3,Bacau,165,165,193,143,144,458,356,329,NaN,NaN,1257.0,979.0
4,Bihor,526,584,613,656,667,700,876,1023,1014.0,1082.0,1293.0,1798.0
5,Bistrita-Nasaud,110,120,149,188,136,116,138,123,173.0,225.0,213.0,209.0
6,Braila,136,136,80,90,112,131,170,199,214.0,250.0,264.0,263.0
7,Botosani,84,70,78,80,77,76,70,74,80.0,124.0,142.0,154.0
8,Brasov,1827,1880,2128,2159,2204,2597,2581,2668,2621.0,2825.0,3124.0,2958.0
9,Bucharest Municipality,32105,32464,33023,36191,38699,41273,45961,48713,54326.0,59145.0,64657.0,69164.0
10,Buzau,320,540,431,500,399,422,436,451,557.0,623.0,569.0,541.0
11,Cluj,1118,1431,1677,1713,1934,1939,2059,2101,2326.0,2894.0,2906.0,3195.0
12,Calarasi,465,463,429,334,353,353,364,299,329.0,417.0,554.0,538.0
13,Caras-Severin,110,207,214,331,287,162,196,216,242.0,278.0,324.0,320.0
14,Constanta,1157,1424,1559,2019,2163,1852,2033,1804,2038.0,1973.0,2377.0,2382.0
15,Covasna,90,89,129,132,140,131,224,283,396.0,391.0,429.0,494.0
16,Dambovita,257,277,350,352,396,334,393,442,426.0,555.0,508.0,593.0
17,Dolj,1083,1068,1251,1135,1198,1267,1335,1334,717.0,788.0,941.0,1016.0
18,Gorj,12,14,13,8,4,3,3,5,7.0,7.0,8.0,-2.0
19,Galati,546,606,513,651,603,844,838,708,744.0,531.0,484.0,485.0
20,Giurgiu,212,132,125,129,169,226,264,363,419.0,437.0,399.0,401.0
21,Hunedoara,313,379,370,379,411,393,411,456,499.0,493.0,560.0,651.0
22,Harghita,113,127,130,106,105,111,123,223,253.0,294.0,464.0,586.0
23,Ilfov,3035,3153,3332,3672,4165,4451,5188,5876,6592.0,7469.0,9495.0,11348.0
24,Ialomita,197,173,212,306,293,301,315,333,357.0,499.0,431.0,461.0
25,Iasi,647,516,448,462,469,460,454,515,543.0,590.0,722.0,795.0
26,Mehedinti,91,106,15,16,5,16,19,14,16.0,20.0,50.0,22.0
27,Maramures,34,176,218,442,476,637,700,710,824.0,929.0,971.0,946.0
28,Mures,1499,1599,1511,1757,1620,1674,1766,1884,1991.0,2151.0,2133.0,2210.0
29,Neamt,146,183,206,192,197,228,191,193,225.0,228.0,217.0,217.0
30,Olt,615,668,707,674,973,942,969,904,973.0,969.0,1045.0,1102.0
31,Prahova,2008,2062,2060,2171,2251,2481,2607,2579,3029.0,3293.0,3372.0,2633.0
32,Sibiu,622,882,803,907,1310,1476,1560,1820,1887.0,2018.0,2063.0,2097.0
33,Salaj,403,478,458,471,457,406,421,451,422.0,495.0,NaN,544.0
34,Satu Mare,236,284,350,391,401,502,553,570,604.0,768.0,829.0,906.0
35,Suceava,457,439,498,459,453,447,445,420,435.0,521.0,558.0,598.0
36,Tulcea,283,282,198,138,322,168,249,295,NaN,NaN,NaN,NaN
37,Timis,2976,3018,3053,3605,3998,4359,4386,4579,4788.0,5240.0,5871.0,5737.0
38,Teleorman,95,101,108,99,79,87,93,117,153.0,158.0,131.0,107.0
39,Valcea,88,133,151,175,182,194,191,183,188.0,189.0,214.0,194.0
40,Vrancea,81,87,86,91,117,121,120,120,114.0,119.0,124.0,107.0
41,Vaslui,85,78,45,34,43,92,66,58,36.0,31.0,15.0,NaN

In [31]:
# Fill missing values in row 3 using linear interpolation and convert the results to integers
df_fdi.loc[3, '2013':] = pd.to_numeric(df_fdi.loc[3, '2013':]).interpolate().round().astype(int)

In [32]:
# Fill missing values in row 33 using linear interpolation and convert the results to integers
df_fdi.loc[33, '2013':] = pd.to_numeric(df_fdi.loc[33, '2013':]).interpolate().round().astype(int)

In [33]:
# Calculate the median value for row 41
median= df_fdi.loc[41, '2013':].median()

# Fill missing values in row 41 with the median value
df_fdi.loc[41, '2013':] = df_fdi.loc[41, '2013':].fillna(median)

In [34]:
# Calculate the median value for row 36
median= df_fdi.loc[36, '2013':].median()

# Fill missing values in row 36 with the median value
df_fdi.loc[36, '2013':] = df_fdi.loc[36, '2013':].fillna(median)

In [35]:
df_fdi

,County,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Alba,886,1192,963,1103,828,828,1065,1024,1270.0,1327.0,1375.0,1580.0
1,Arges,1450,582,791,1037,1117,1233,1425,1521,1606.0,1743.0,1850.0,1962.0
2,Arad,760,854,959,1079,1216,1011,914,1103,1498.0,1362.0,1582.0,1739.0
3,Bacau,165,165,193,143,144,458,356,329,638.0,948.0,1257.0,979.0
4,Bihor,526,584,613,656,667,700,876,1023,1014.0,1082.0,1293.0,1798.0
5,Bistrita-Nasaud,110,120,149,188,136,116,138,123,173.0,225.0,213.0,209.0
6,Braila,136,136,80,90,112,131,170,199,214.0,250.0,264.0,263.0
7,Botosani,84,70,78,80,77,76,70,74,80.0,124.0,142.0,154.0
8,Brasov,1827,1880,2128,2159,2204,2597,2581,2668,2621.0,2825.0,3124.0,2958.0
9,Bucharest Municipality,32105,32464,33023,36191,38699,41273,45961,48713,54326.0,59145.0,64657.0,69164.0
10,Buzau,320,540,431,500,399,422,436,451,557.0,623.0,569.0,541.0
11,Cluj,1118,1431,1677,1713,1934,1939,2059,2101,2326.0,2894.0,2906.0,3195.0
12,Calarasi,465,463,429,334,353,353,364,299,329.0,417.0,554.0,538.0
13,Caras-Severin,110,207,214,331,287,162,196,216,242.0,278.0,324.0,320.0
14,Constanta,1157,1424,1559,2019,2163,1852,2033,1804,2038.0,1973.0,2377.0,2382.0
15,Covasna,90,89,129,132,140,131,224,283,396.0,391.0,429.0,494.0
16,Dambovita,257,277,350,352,396,334,393,442,426.0,555.0,508.0,593.0
17,Dolj,1083,1068,1251,1135,1198,1267,1335,1334,717.0,788.0,941.0,1016.0
18,Gorj,12,14,13,8,4,3,3,5,7.0,7.0,8.0,-2.0
19,Galati,546,606,513,651,603,844,838,708,744.0,531.0,484.0,485.0
20,Giurgiu,212,132,125,129,169,226,264,363,419.0,437.0,399.0,401.0
21,Hunedoara,313,379,370,379,411,393,411,456,499.0,493.0,560.0,651.0
22,Harghita,113,127,130,106,105,111,123,223,253.0,294.0,464.0,586.0
23,Ilfov,3035,3153,3332,3672,4165,4451,5188,5876,6592.0,7469.0,9495.0,11348.0
24,Ialomita,197,173,212,306,293,301,315,333,357.0,499.0,431.0,461.0
25,Iasi,647,516,448,462,469,460,454,515,543.0,590.0,722.0,795.0
26,Mehedinti,91,106,15,16,5,16,19,14,16.0,20.0,50.0,22.0
27,Maramures,34,176,218,442,476,637,700,710,824.0,929.0,971.0,946.0
28,Mures,1499,1599,1511,1757,1620,1674,1766,1884,1991.0,2151.0,2133.0,2210.0
29,Neamt,146,183,206,192,197,228,191,193,225.0,228.0,217.0,217.0
30,Olt,615,668,707,674,973,942,969,904,973.0,969.0,1045.0,1102.0
31,Prahova,2008,2062,2060,2171,2251,2481,2607,2579,3029.0,3293.0,3372.0,2633.0
32,Sibiu,622,882,803,907,1310,1476,1560,1820,1887.0,2018.0,2063.0,2097.0
33,Salaj,403,478,458,471,457,406,421,451,422.0,495.0,520.0,544.0
34,Satu Mare,236,284,350,391,401,502,553,570,604.0,768.0,829.0,906.0
35,Suceava,457,439,498,459,453,447,445,420,435.0,521.0,558.0,598.0
36,Tulcea,283,282,198,138,322,168,249,295,265.5,265.5,265.5,265.5
37,Timis,2976,3018,3053,3605,3998,4359,4386,4579,4788.0,5240.0,5871.0,5737.0
38,Teleorman,95,101,108,99,79,87,93,117,153.0,158.0,131.0,107.0
39,Valcea,88,133,151,175,182,194,191,183,188.0,189.0,214.0,194.0
40,Vrancea,81,87,86,91,117,121,120,120,114.0,119.0,124.0,107.0
41,Vaslui,85,78,45,34,43,92,66,58,36.0,31.0,15.0,45.0

In [36]:
# Convert all columns except the first one to integer type
df_fdi[df_fdi.columns[1:]] = df_fdi[df_fdi.columns[1:]].astype(int)
# Display the updated DataFrame
df_fdi

,County,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Alba,886,1192,963,1103,828,828,1065,1024,1270,1327,1375,1580
1,Arges,1450,582,791,1037,1117,1233,1425,1521,1606,1743,1850,1962
2,Arad,760,854,959,1079,1216,1011,914,1103,1498,1362,1582,1739
3,Bacau,165,165,193,143,144,458,356,329,638,948,1257,979
4,Bihor,526,584,613,656,667,700,876,1023,1014,1082,1293,1798
5,Bistrita-Nasaud,110,120,149,188,136,116,138,123,173,225,213,209
6,Braila,136,136,80,90,112,131,170,199,214,250,264,263
7,Botosani,84,70,78,80,77,76,70,74,80,124,142,154
8,Brasov,1827,1880,2128,2159,2204,2597,2581,2668,2621,2825,3124,2958
9,Bucharest Municipality,32105,32464,33023,36191,38699,41273,45961,48713,54326,59145,64657,69164
10,Buzau,320,540,431,500,399,422,436,451,557,623,569,541
11,Cluj,1118,1431,1677,1713,1934,1939,2059,2101,2326,2894,2906,3195
12,Calarasi,465,463,429,334,353,353,364,299,329,417,554,538
13,Caras-Severin,110,207,214,331,287,162,196,216,242,278,324,320
14,Constanta,1157,1424,1559,2019,2163,1852,2033,1804,2038,1973,2377,2382
15,Covasna,90,89,129,132,140,131,224,283,396,391,429,494
16,Dambovita,257,277,350,352,396,334,393,442,426,555,508,593
17,Dolj,1083,1068,1251,1135,1198,1267,1335,1334,717,788,941,1016
18,Gorj,12,14,13,8,4,3,3,5,7,7,8,-2
19,Galati,546,606,513,651,603,844,838,708,744,531,484,485
20,Giurgiu,212,132,125,129,169,226,264,363,419,437,399,401
21,Hunedoara,313,379,370,379,411,393,411,456,499,493,560,651
22,Harghita,113,127,130,106,105,111,123,223,253,294,464,586
23,Ilfov,3035,3153,3332,3672,4165,4451,5188,5876,6592,7469,9495,11348
24,Ialomita,197,173,212,306,293,301,315,333,357,499,431,461
25,Iasi,647,516,448,462,469,460,454,515,543,590,722,795
26,Mehedinti,91,106,15,16,5,16,19,14,16,20,50,22
27,Maramures,34,176,218,442,476,637,700,710,824,929,971,946
28,Mures,1499,1599,1511,1757,1620,1674,1766,1884,1991,2151,2133,2210
29,Neamt,146,183,206,192,197,228,191,193,225,228,217,217
30,Olt,615,668,707,674,973,942,969,904,973,969,1045,1102
31,Prahova,2008,2062,2060,2171,2251,2481,2607,2579,3029,3293,3372,2633
32,Sibiu,622,882,803,907,1310,1476,1560,1820,1887,2018,2063,2097
33,Salaj,403,478,458,471,457,406,421,451,422,495,520,544
34,Satu Mare,236,284,350,391,401,502,553,570,604,768,829,906
35,Suceava,457,439,498,459,453,447,445,420,435,521,558,598
36,Tulcea,283,282,198,138,322,168,249,295,265,265,265,265
37,Timis,2976,3018,3053,3605,3998,4359,4386,4579,4788,5240,5871,5737
38,Teleorman,95,101,108,99,79,87,93,117,153,158,131,107
39,Valcea,88,133,151,175,182,194,191,183,188,189,214,194
40,Vrancea,81,87,86,91,117,121,120,120,114,119,124,107
41,Vaslui,85,78,45,34,43,92,66,58,36,31,15,45

In [37]:
# Add the prefix 'F_' to all column names
new_columns = ['F_' + x for x in df_fdi.columns]

# Rename the first column as 'County'
new_columns[0] = 'County'

# Assign the updated column names to the DataFrame
df_fdi.columns = new_columns

# Display the first rows of the DataFrame
df_fdi.head()

,County,F_2013,F_2014,F_2015,F_2016,F_2017,F_2018,F_2019,F_2020,F_2021,F_2022,F_2023,F_2024
0,Alba,886,1192,963,1103,828,828,1065,1024,1270,1327,1375,1580
1,Arges,1450,582,791,1037,1117,1233,1425,1521,1606,1743,1850,1962
2,Arad,760,854,959,1079,1216,1011,914,1103,1498,1362,1582,1739
3,Bacau,165,165,193,143,144,458,356,329,638,948,1257,979
4,Bihor,526,584,613,656,667,700,876,1023,1014,1082,1293,1798

## Calculate ISD per capita

In [57]:
# Import the CSV file containing population data
# Rename the columns of the dataset
# Skip the first row from the file (original header)
df_pop_2013_2024 = pd.read_csv('Data/Population/exportPivot_POP105A_1.csv', delimiter = ',', names = ['Age', 'Sex', 'Area', 'County', 'Years', 'Persons', 'Population'], skiprows = 1)

# Display the resulting DataFrame
df_pop_2013_2024

       Age     Sex    Area  County       Years             Persons  Population
0    Total   Total   Total   Bihor   Year 2013   Number of persons      575270
1    Total   Total   Total   Bihor   Year 2014   Number of persons      573769
2    Total   Total   Total   Bihor   Year 2015   Number of persons      572057
3    Total   Total   Total   Bihor   Year 2016   Number of persons      568969
4    Total   Total   Total   Bihor   Year 2017   Number of persons      566381
..     ...     ...     ...     ...         ...                 ...         ...
499  Total   Total   Total   Timis   Year 2020   Number of persons      706585
500  Total   Total   Total   Timis   Year 2021   Number of persons      706497
501  Total   Total   Total   Timis   Year 2022   Number of persons      652238
502  Total   Total   Total   Timis   Year 2023   Number of persons      658515
503  Total   Total   Total   Timis   Year 2024   Number of persons      663543

[504 rows x 7 columns]

In [58]:
# Remove unnecessary columns from the DataFrame
df_pop_2013_2024 = df_pop_2013_2024.drop(['Age', 'Sex', 'Area', 'Persons'], axis = 1)

# Display the cleaned DataFrame
df_pop_2013_2024

     County       Years  Population
0     Bihor   Year 2013      575270
1     Bihor   Year 2014      573769
2     Bihor   Year 2015      572057
3     Bihor   Year 2016      568969
4     Bihor   Year 2017      566381
..      ...         ...         ...
499   Timis   Year 2020      706585
500   Timis   Year 2021      706497
501   Timis   Year 2022      652238
502   Timis   Year 2023      658515
503   Timis   Year 2024      663543

[504 rows x 3 columns]

In [59]:
# Remove the 'Year' prefix from the values in the 'Years' column
df_pop_2013_2024['Years'] = df_pop_2013_2024['Years'].str.strip('Year ')

# Display the updated DataFrame
df_pop_2013_2024

     County Years  Population
0     Bihor  2013      575270
1     Bihor  2014      573769
2     Bihor  2015      572057
3     Bihor  2016      568969
4     Bihor  2017      566381
..      ...   ...         ...
499   Timis  2020      706585
500   Timis  2021      706497
501   Timis  2022      652238
502   Timis  2023      658515
503   Timis  2024      663543

[504 rows x 3 columns]

In [60]:
# Reshape the DataFrame to display counties as rows and years as columns
df_pop_2013_2024 = df_pop_2013_2024.pivot(index = 'County', columns = 'Years', values = 'Population')

# Display the first rows of the pivot table
df_pop_2013_2024.head()

Years,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
County,,,,,,,,,,,,
Alba,339517,337717,335915,333488,330954,328264,325475,324071,321199,325715,325838,325697
Arad,429625,428079,426517,424075,421954,419135,417274,415914,413035,410282,410451,410871
Arges,606789,604153,600301,595764,590522,585713,579904,575197,567851,566913,565747,564829
Bacau,609948,606975,604567,600549,595534,591053,585548,582495,576683,599435,597504,595888
Bihor,575270,573769,572057,568969,566381,564171,561621,560646,557836,552031,554016,555957

In [61]:
# Reset the index to transform 'County' from index into a regular column
df_pop_2013_2024 = df_pop_2013_2024.reset_index()

In [62]:
# Remove the name of the columns index
df_pop_2013_2024.columns.name = None

In [63]:
# Display the first rows of the pivot table
df_pop_2013_2024.head()

,County,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Alba,339517,337717,335915,333488,330954,328264,325475,324071,321199,325715,325838,325697
1,Arad,429625,428079,426517,424075,421954,419135,417274,415914,413035,410282,410451,410871
2,Arges,606789,604153,600301,595764,590522,585713,579904,575197,567851,566913,565747,564829
3,Bacau,609948,606975,604567,600549,595534,591053,585548,582495,576683,599435,597504,595888
4,Bihor,575270,573769,572057,568969,566381,564171,561621,560646,557836,552031,554016,555957

In [64]:
# Create a copy of the DataFrame
df_pop_2013_2024 = df_pop_2013_2024.copy()

In [65]:
# Add the prefix 'P_' to all column names
new_columns = ['P_' + x for x in df_pop_2013_2024]

# Rename the first column as 'County'
new_columns[0] = 'County'

# Assign the updated column names to the DataFrame
df_pop_2013_2024.columns = new_columns

# Display the first rows of the Population DataFrame
df_pop_2013_2024.head()

,County,P_2013,P_2014,P_2015,P_2016,P_2017,P_2018,P_2019,P_2020,P_2021,P_2022,P_2023,P_2024
0,Alba,339517,337717,335915,333488,330954,328264,325475,324071,321199,325715,325838,325697
1,Arad,429625,428079,426517,424075,421954,419135,417274,415914,413035,410282,410451,410871
2,Arges,606789,604153,600301,595764,590522,585713,579904,575197,567851,566913,565747,564829
3,Bacau,609948,606975,604567,600549,595534,591053,585548,582495,576683,599435,597504,595888
4,Bihor,575270,573769,572057,568969,566381,564171,561621,560646,557836,552031,554016,555957

In [66]:
# Display the first rows of the FDI DataFrame
df_fdi.head()

,County,F_2013,F_2014,F_2015,F_2016,F_2017,F_2018,F_2019,F_2020,F_2021,F_2022,F_2023,F_2024
0,Alba,886,1192,963,1103,828,828,1065,1024,1270,1327,1375,1580
1,Arges,1450,582,791,1037,1117,1233,1425,1521,1606,1743,1850,1962
2,Arad,760,854,959,1079,1216,1011,914,1103,1498,1362,1582,1739
3,Bacau,165,165,193,143,144,458,356,329,638,948,1257,979
4,Bihor,526,584,613,656,667,700,876,1023,1014,1082,1293,1798

In [67]:
# Remove leading spaces from the values in the 'County' column
df_pop_2013_2024['County'] = df_pop_2013_2024['County'].str.lstrip(' ')

In [68]:
# Merge the FDI and population DataFrames based on the 'County' column
df_fdi_capita = pd.merge(df_fdi, df_pop_2013_2024, on = 'County', how = 'inner')

# Display the merged DataFrame
df_fdi_capita

,County,F_2013,F_2014,F_2015,F_2016,F_2017,F_2018,F_2019,F_2020,F_2021,...,P_2015,P_2016,P_2017,P_2018,P_2019,P_2020,P_2021,P_2022,P_2023,P_2024
0,Alba,886,1192,963,1103,828,828,1065,1024,1270,...,335915,333488,330954,328264,325475,324071,321199,325715,325838,325697
1,Arges,1450,582,791,1037,1117,1233,1425,1521,1606,...,600301,595764,590522,585713,579904,575197,567851,566913,565747,564829
2,Arad,760,854,959,1079,1216,1011,914,1103,1498,...,426517,424075,421954,419135,417274,415914,413035,410282,410451,410871
3,Bacau,165,165,193,143,144,458,356,329,638,...,604567,600549,595534,591053,585548,582495,576683,599435,597504,595888
4,Bihor,526,584,613,656,667,700,876,1023,1014,...,572057,568969,566381,564171,561621,560646,557836,552031,554016,555957
5,Bistrita-Nasaud,110,120,149,188,136,116,138,123,173,...,283255,282495,281387,280058,278868,278033,276517,295351,296140,297082
6,Braila,136,136,80,90,112,131,170,199,214,...,308203,303608,299087,294097,289534,286021,280796,280196,277021,274751
7,Botosani,84,70,78,80,77,76,70,74,80,...,399273,394625,390320,385268,380142,377679,373239,391108,389815,389748
8,Brasov,1827,1880,2128,2159,2204,2597,2581,2668,2621,...,551160,550934,550789,551185,552390,554014,553807,548254,552813,557129
9,Bucharest Municipality,32105,32464,33023,36191,38699,41273,45961,48713,54326,...,1853638,1843962,1826579,1828869,1832802,1841052,1828781,1722974,1724966,1721784
10,Buzau,320,540,431,500,399,422,436,451,557,...,436478,431015,425842,419831,413808,409388,403937,403817,400823,398344
11,Cluj,1118,1431,1677,1713,1934,1939,2059,2101,2326,...,700982,701258,702780,704619,706952,709872,710664,683028,688844,693507
12,Calarasi,465,463,429,334,353,353,364,299,329,...,298763,295505,292841,288061,284393,280483,278105,281980,280468,279349
13,Caras-Severin,110,207,214,331,287,162,196,216,242,...,286205,282467,279123,275041,271379,269810,266592,246319,244904,243685
14,Constanta,1157,1424,1559,2019,2163,1852,2033,1804,2038,...,683329,681054,678316,676095,673764,672451,668329,656017,657055,657419
15,Covasna,90,89,129,132,140,131,224,283,396,...,207569,206279,204929,203471,202113,201503,200083,199912,199795,199675
16,Dambovita,257,277,350,352,396,334,393,442,426,...,509552,505219,501269,496213,491368,487387,483351,478599,477197,476962
17,Dolj,1083,1068,1251,1135,1198,1267,1335,1334,717,...,646620,641040,635606,631026,626017,622148,616653,599580,599631,598371
18,Gorj,12,14,13,8,4,3,3,5,7,...,331428,327537,323634,319903,315508,312035,307972,313025,311301,310056
19,Galati,546,606,513,651,603,844,838,708,744,...,524751,520058,515297,510865,506135,503506,499364,495030,494280,493009
20,Giurgiu,212,132,125,129,169,226,264,363,419,...,276664,274570,273989,269239,266207,263329,261109,260203,258751,258661
21,Hunedoara,313,379,370,379,411,393,411,456,499,...,403701,398950,393198,388614,383787,380511,374298,360692,357563,354879
22,Harghita,113,127,130,106,105,111,123,223,253,...,309133,307555,305676,304219,302291,301521,299163,291633,291810,292148
23,Ilfov,3035,3153,3332,3672,4165,4451,5188,5876,6592,...,430805,444241,460486,473422,485307,486869,503675,545407,564833,583663
24,Ialomita,197,173,212,306,293,301,315,333,357,...,267230,264733,262237,259143,256499,255032,252735,250451,249852,249364
25,Iasi,647,516,448,462,469,460,454,515,543,...,787589,788659,789935,791753,794706,794979,797131,765720,774025,778689
26,Mehedinti,91,106,15,16,5,16,19,14,16,...,256011,252600,249336,244960,241153,238830,236362,233636,231398,230094
27,Maramures,34,176,218,442,476,637,700,710,824,...,470714,468333,465423,463306,460756,458927,455160,451499,451728,451881
28,Mures,1499,1599,1511,1757,1620,1674,1766,1884,1991,...,546532,543726,540719,538214,535202,533355,529593,518991,519395,519831
29,Neamt,146,183,206,192,197,228,191,193,225,...,459457,455643,451544,447232,442132,439179,433852,452057,449345,447776
30,Olt,615,668,707,674,973,942,969,904,973,...,418463,412491,407717,400763,394448,389906,385935,381731,378567,376539
31,Prahova,2008,2062,2060,2171,2251,2481,2607,2579,3029,...,747634,740483,732847,725599,718098,712725,703580,694502,691246,688976
32,Sibiu,622,882,803,907,1310,1476,1560,1820,1887,...,400230,399982,399724,400018,400988,401352,400291,388896,391433,393581
33,Salaj,403,478,458,471,457,406,421,451,422,...,219039,217331,215878,213761,211663,209982,209114,211329,210652,210656
34,Satu Mare,236,284,350,391,401,502,553,570,604,...,339987,338181,336543,334589,332610,331500,329535,330363,330662,330701
35,Suceava,457,439,498,459,453,447,445,420,435,...,631309,629733,628316,627439,625969,625431,622665,640816,642275,645196
36,Tulcea,283,282,198,138,322,168,249,295,265,...,206013,203196,200706,197734,194439,192163,189747,192566,190994,189336
37,Timis,2976,3018,3053,3605,3998,4359,4386,4579,4788,...,695760,696720,698275,701506,705292,706585,706497,652238,658515,663543
38,Teleorman,95,101,108,99,79,87,93,117,153,...,361615,355281,349628,341447,334217,329058,324405,322245,318043,315482
39,Valcea,88,133,151,175,182,194,191,183,188,...,363270,359814,356647,353161,350089,348495,346039,341630,340914,340637
40,Vrancea,81,87,86,91,117,121,120,120,114,...,333808,330937,328057,324437,320722,317778,314494,334066,333154,332313
41,Vaslui,85,78,45,34,43,92,66,58,36,...,390015,387525,383924,379987,374303,373127,369345,372861,371464,369517

In [69]:
# Calculate FDI per 1,000 inhabitants for each county and year
df_fdi_capita_2013_2024 = df_fdi_capita.iloc[:, 1:13].values / df_fdi_capita.iloc[:, 13:].values * 1000

# Convert the result into a DataFrame and clean the year column names
df_fdi_capita_2013_2024 = pd.DataFrame(df_fdi_capita_2013_2024, columns = df_fdi_capita.columns[1:13].str.lstrip('F_'))

# Add the 'County' column as the first column
df_fdi_capita_2013_2024.insert(0, 'County', df_fdi_capita['County'].values)

# Display the resulting DataFrame
df_fdi_capita_2013_2024

,County,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Alba,2.609590,3.529582,2.866797,3.307465,2.501858,2.522360,3.272141,3.159801,3.953935,4.074114,4.219888,4.851135
1,Arges,2.389628,0.963332,1.317672,1.740622,1.891547,2.105127,2.457303,2.644311,2.828207,3.074546,3.270013,3.473618
2,Arad,1.768985,1.994959,2.248445,2.544361,2.881831,2.412111,2.190407,2.651991,3.626811,3.319668,3.854297,4.232472
3,Bacau,0.270515,0.271840,0.319237,0.238115,0.241800,0.774888,0.607977,0.564812,1.106327,1.581489,2.103752,1.642926
4,Bihor,0.914353,1.017831,1.071572,1.152963,1.177652,1.240759,1.559771,1.824681,1.817739,1.960035,2.333868,3.234063
5,Bistrita-Nasaud,0.387081,0.422669,0.526028,0.665499,0.483320,0.414200,0.494858,0.442394,0.625640,0.761805,0.719254,0.703509
6,Braila,0.430928,0.435685,0.259569,0.296435,0.374473,0.445431,0.587150,0.695753,0.762119,0.892233,0.952996,0.957230
7,Botosani,0.206729,0.173609,0.195355,0.202724,0.197274,0.197265,0.184142,0.195934,0.214340,0.317048,0.364275,0.395127
8,Brasov,3.317517,3.412523,3.860948,3.918800,4.001532,4.711667,4.672423,4.815763,4.732696,5.152721,5.651097,5.309363
9,Bucharest Municipality,17.119115,17.401717,17.815237,19.626760,21.186601,22.567499,25.076904,26.459329,29.706127,34.327274,37.483058,40.169963
10,Buzau,0.719112,1.224445,0.987450,1.160052,0.936967,1.005166,1.053629,1.101644,1.378928,1.542778,1.419579,1.358123
11,Cluj,1.602966,2.046926,2.392358,2.442753,2.751928,2.751842,2.912503,2.959689,3.272995,4.237015,4.218662,4.607019
12,Calarasi,1.530204,1.536542,1.435921,1.130269,1.205432,1.225435,1.279919,1.066018,1.183006,1.478828,1.975270,1.925906
13,Caras-Severin,0.376875,0.716236,0.747716,1.171818,1.028221,0.589003,0.722237,0.800563,0.907754,1.128618,1.322967,1.313171
14,Constanta,1.690389,2.080679,2.281478,2.964523,3.188779,2.739260,3.017377,2.682723,3.049396,3.007544,3.617658,3.623260
15,Covasna,0.430671,0.426597,0.621480,0.639910,0.683163,0.643826,1.108291,1.404446,1.979179,1.955861,2.147201,2.474020
16,Dambovita,0.498426,0.540234,0.686878,0.696728,0.789995,0.673098,0.799808,0.906877,0.881347,1.159635,1.064550,1.243286
17,Dolj,1.654809,1.641140,1.934676,1.770560,1.884815,2.007841,2.132530,2.144184,1.162728,1.314253,1.569298,1.697943
18,Gorj,0.035609,0.041810,0.039224,0.024425,0.012360,0.009378,0.009508,0.016024,0.022729,0.022362,0.025699,-0.006450
19,Galati,1.028415,1.147258,0.977607,1.251783,1.170199,1.652100,1.655685,1.406140,1.489895,1.072662,0.979202,0.983755
20,Giurgiu,0.751802,0.474014,0.451812,0.469826,0.616813,0.839403,0.991709,1.378504,1.604694,1.679458,1.542023,1.550292
21,Hunedoara,0.759090,0.928917,0.916520,0.949994,1.045275,1.011286,1.070907,1.198388,1.333162,1.366817,1.566158,1.834428
22,Harghita,0.363529,0.409202,0.420531,0.344654,0.343501,0.364869,0.406893,0.739584,0.845693,1.008116,1.590076,2.005833
23,Ilfov,7.459660,7.545770,7.734358,8.265784,9.044792,9.401760,10.690140,12.068955,13.087805,13.694360,16.810278,19.442726
24,Ialomita,0.726857,0.642201,0.793324,1.155882,1.117310,1.161521,1.228075,1.305718,1.412547,1.992406,1.725021,1.848703
25,Iasi,0.834661,0.660266,0.568825,0.585805,0.593720,0.580989,0.571280,0.647816,0.681193,0.770517,0.932786,1.020947
26,Mehedinti,0.347766,0.409225,0.058591,0.063341,0.020053,0.065317,0.078788,0.058619,0.067693,0.085603,0.216078,0.095613
27,Maramures,0.071713,0.372500,0.463126,0.943773,1.022726,1.374901,1.519242,1.547087,1.810352,2.057590,2.149524,2.093472
28,Mures,2.729937,2.918624,2.764705,3.231407,2.996011,3.110287,3.299689,3.532356,3.759491,4.144581,4.106701,4.251382
29,Neamt,0.314142,0.396010,0.448355,0.421383,0.436281,0.509803,0.431998,0.439456,0.518610,0.504361,0.482925,0.484617
30,Olt,1.436379,1.577537,1.689516,1.633975,2.386459,2.350516,2.456598,2.318508,2.521150,2.538437,2.760410,2.926656
31,Prahova,2.653856,2.740545,2.755359,2.931870,3.071582,3.419244,3.630424,3.618506,4.305125,4.741527,4.878148,3.821614
32,Sibiu,1.553990,2.203524,2.006346,2.267602,3.277261,3.689834,3.890391,4.534673,4.714071,5.189048,5.270378,5.328001
33,Salaj,1.817895,2.168007,2.090952,2.167201,2.116936,1.899317,1.989011,2.147803,2.018038,2.342319,2.468526,2.582409
34,Satu Mare,0.689820,0.832615,1.029451,1.156186,1.191527,1.500348,1.662608,1.719457,1.832886,2.324716,2.507092,2.739635
35,Suceava,0.722861,0.694884,0.788837,0.728880,0.720975,0.712420,0.710898,0.671537,0.698610,0.813026,0.868787,0.926850
36,Tulcea,1.346856,1.353888,0.961104,0.679147,1.604337,0.849626,1.280607,1.535155,1.396597,1.376152,1.387478,1.399628
37,Timis,4.308279,4.353276,4.388007,5.174245,5.725538,6.213774,6.218701,6.480466,6.777099,8.033877,8.915514,8.646011
38,Teleorman,0.255237,0.275025,0.298660,0.278653,0.225954,0.254798,0.278262,0.355560,0.471633,0.490310,0.411894,0.339164
39,Valcea,0.239507,0.363689,0.415669,0.486362,0.510309,0.549325,0.545576,0.525115,0.543291,0.553230,0.627724,0.569521
40,Vrancea,0.240162,0.259131,0.257633,0.274977,0.356645,0.372954,0.374156,0.377622,0.362487,0.356217,0.372200,0.321986
41,Vaslui,0.217733,0.200065,0.115380,0.087736,0.112001,0.242114,0.176328,0.155443,0.097470,0.083141,0.040381,0.121781

In [95]:
# Transform the DataFrame from wide format to panel format
df_fdi_capita_panel = df_fdi_capita_2013_2024.melt( id_vars = 'County', var_name = 'Years', value_name = 'FDI per capita')

# Display the resulting panel DataFrame
df_fdi_capita_panel

        County Years  FDI per capita
0         Alba  2013        2.609590
1        Arges  2013        2.389628
2         Arad  2013        1.768985
3        Bacau  2013        0.270515
4        Bihor  2013        0.914353
..         ...   ...             ...
499      Timis  2024        8.646011
500  Teleorman  2024        0.339164
501     Valcea  2024        0.569521
502    Vrancea  2024        0.321986
503     Vaslui  2024        0.121781

[504 rows x 3 columns]

In [96]:
# Export the panel DataFrame to an Excel file without including the index
df_fdi_capita_panel.to_excel('fdi_capita_county_2013_2024.xlsx', index = False)

## Processing Enterprises

In [84]:
# Import the CSV file containing active enterprises data
# Rename the columns of the dataset
# Skip the first row from the file (original header)
df_enterprises = pd.read_csv('Data/Active enterprises/exportPivot_INT101O.csv', delimiter = ',', names = ['CANE', 'Size clases', 'County', 'Years', 'Number', 'Enterprises'], skiprows = 1)

# Display the resulting DataFrame
df_enterprises

      CANE Size clases  County       Years   Number  Enterprises
0    Total       Total   Bihor   Year 2013   Number        16302
1    Total       Total   Bihor   Year 2014   Number        17360
2    Total       Total   Bihor   Year 2015   Number        17424
3    Total       Total   Bihor   Year 2016   Number        17994
4    Total       Total   Bihor   Year 2017   Number        18902
..     ...         ...     ...         ...      ...          ...
499  Total       Total   Timis   Year 2020   Number        27850
500  Total       Total   Timis   Year 2021   Number        29249
501  Total       Total   Timis   Year 2022   Number        30195
502  Total       Total   Timis   Year 2023   Number        32082
503  Total       Total   Timis   Year 2024   Number        32597

[504 rows x 6 columns]

In [85]:
# Remove unnecessary columns from the DataFrame
df_enterprises = df_enterprises.drop(['CANE', 'Size clases', 'Number'], axis = 1)

# Display the cleaned DataFrame
df_enterprises

     County       Years  Enterprises
0     Bihor   Year 2013        16302
1     Bihor   Year 2014        17360
2     Bihor   Year 2015        17424
3     Bihor   Year 2016        17994
4     Bihor   Year 2017        18902
..      ...         ...          ...
499   Timis   Year 2020        27850
500   Timis   Year 2021        29249
501   Timis   Year 2022        30195
502   Timis   Year 2023        32082
503   Timis   Year 2024        32597

[504 rows x 3 columns]

In [86]:
# Remove the 'Year' prefix from the values in the 'Years' column
df_enterprises['Years'] = df_enterprises['Years'].str.lstrip('Year ')

In [87]:
# Reshape the DataFrame to display counties as rows and years as columns
df_enterprises = df_enterprises.pivot(columns = 'Years', index = 'County', values = 'Enterprises')

# Display the first rows of the pivot table
df_enterprises.head()

Years,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
County,,,,,,,,,,,,
Alba,7321,7563,7730,7923,8161,8536,9110,9745,10221,10416,10996,11078
Arad,10511,10972,11097,11384,11998,12548,12986,13568,14173,14466,15117,15229
Arges,13342,14040,14415,14978,16066,16922,17511,18486,19226,19663,20753,20947
Bacau,10577,10930,10937,11155,11688,12099,12292,13148,13617,14256,14759,15133
Bihor,16302,17360,17424,17994,18902,19617,19821,20854,21762,22513,23889,24446

In [88]:
# Remove the name of the columns index
df_enterprises.columns.name = None

In [89]:
# Reset the index to transform 'County' from index into a regular column
df_enterprises = df_enterprises.reset_index()

In [ ]:
# Remove leading spaces from the values in the 'County' column
df_enterprises['County'] = df_enterprises['County'].str.lstrip(' ')

In [91]:
# Add the prefix 'E_' to all column names
new_columns = ['E_' + x for x in df_enterprises]

# Rename the first column as 'County'
new_columns[0] = 'County'

# Assign the updated column names to the DataFrame
df_enterprises.columns = new_columns

# Display the first rows of the DataFrame
df_enterprises.head()

,County,E_2013,E_2014,E_2015,E_2016,E_2017,E_2018,E_2019,E_2020,E_2021,E_2022,E_2023,E_2024
0,Alba,7321,7563,7730,7923,8161,8536,9110,9745,10221,10416,10996,11078
1,Arad,10511,10972,11097,11384,11998,12548,12986,13568,14173,14466,15117,15229
2,Arges,13342,14040,14415,14978,16066,16922,17511,18486,19226,19663,20753,20947
3,Bacau,10577,10930,10937,11155,11688,12099,12292,13148,13617,14256,14759,15133
4,Bihor,16302,17360,17424,17994,18902,19617,19821,20854,21762,22513,23889,24446

In [92]:
# Merge the enterprises and population DataFrames based on the 'County' column
df_enterprises_capita = pd.merge(df_enterprises, df_pop_2013_2024, how = 'inner', on = 'County')

# Display the merged DataFrame
df_enterprises_capita

,County,E_2013,E_2014,E_2015,E_2016,E_2017,E_2018,E_2019,E_2020,E_2021,...,P_2015,P_2016,P_2017,P_2018,P_2019,P_2020,P_2021,P_2022,P_2023,P_2024
0,Alba,7321,7563,7730,7923,8161,8536,9110,9745,10221,...,335915,333488,330954,328264,325475,324071,321199,325715,325838,325697
1,Arad,10511,10972,11097,11384,11998,12548,12986,13568,14173,...,426517,424075,421954,419135,417274,415914,413035,410282,410451,410871
2,Arges,13342,14040,14415,14978,16066,16922,17511,18486,19226,...,600301,595764,590522,585713,579904,575197,567851,566913,565747,564829
3,Bacau,10577,10930,10937,11155,11688,12099,12292,13148,13617,...,604567,600549,595534,591053,585548,582495,576683,599435,597504,595888
4,Bihor,16302,17360,17424,17994,18902,19617,19821,20854,21762,...,572057,568969,566381,564171,561621,560646,557836,552031,554016,555957
5,Bistrita-Nasaud,5904,6123,6221,6497,6976,7453,7762,8568,8913,...,283255,282495,281387,280058,278868,278033,276517,295351,296140,297082
6,Botosani,3773,3933,4012,4050,4328,4448,4581,5050,5229,...,399273,394625,390320,385268,380142,377679,373239,391108,389815,389748
7,Braila,6102,6206,6195,6163,6347,6527,6668,6939,7176,...,308203,303608,299087,294097,289534,286021,280796,280196,277021,274751
8,Brasov,17295,17911,18185,18726,19801,20696,21484,22763,23810,...,551160,550934,550789,551185,552390,554014,553807,548254,552813,557129
9,Bucharest Municipality,103218,109064,109455,110926,113977,116603,115872,119798,124399,...,1853638,1843962,1826579,1828869,1832802,1841052,1828781,1722974,1724966,1721784
10,Buzau,8653,8943,8990,9230,9620,9773,9952,10380,10760,...,436478,431015,425842,419831,413808,409388,403937,403817,400823,398344
11,Calarasi,4315,4370,4511,4576,4722,4970,5093,5349,5591,...,298763,295505,292841,288061,284393,280483,278105,281980,280468,279349
12,Caras-Severin,4588,4749,4690,4640,4792,4877,4865,5092,5160,...,286205,282467,279123,275041,271379,269810,266592,246319,244904,243685
13,Cluj,25375,27153,28126,29754,32028,34107,34989,36580,38695,...,700982,701258,702780,704619,706952,709872,710664,683028,688844,693507
14,Constanta,20284,20816,20684,20831,21831,22606,23292,24426,25411,...,683329,681054,678316,676095,673764,672451,668329,656017,657055,657419
15,Covasna,3777,3792,3672,3788,3996,4155,4329,4517,4589,...,207569,206279,204929,203471,202113,201503,200083,199912,199795,199675
16,Dambovita,6455,6728,6945,7257,7823,8300,8899,9550,10093,...,509552,505219,501269,496213,491368,487387,483351,478599,477197,476962
17,Dolj,13400,13979,14014,14226,14788,15234,15885,16911,17498,...,646620,641040,635606,631026,626017,622148,616653,599580,599631,598371
18,Galati,10975,11292,11456,11809,12133,12512,12624,13252,13609,...,524751,520058,515297,510865,506135,503506,499364,495030,494280,493009
19,Giurgiu,4038,4296,4450,4473,4740,4939,5324,5837,6354,...,276664,274570,273989,269239,266207,263329,261109,260203,258751,258661
20,Gorj,5776,5921,5932,6085,6525,6784,7224,7663,8045,...,331428,327537,323634,319903,315508,312035,307972,313025,311301,310056
21,Harghita,7105,7289,7114,7157,7343,7504,7804,7979,8174,...,309133,307555,305676,304219,302291,301521,299163,291633,291810,292148
22,Hunedoara,8502,8755,8659,8696,8932,9196,9497,10020,10406,...,403701,398950,393198,388614,383787,380511,374298,360692,357563,354879
23,Ialomita,3914,4019,4067,4185,4307,4530,4714,4913,5152,...,267230,264733,262237,259143,256499,255032,252735,250451,249852,249364
24,Iasi,14196,14838,15119,15820,17121,18221,18826,20617,21966,...,787589,788659,789935,791753,794706,794979,797131,765720,774025,778689
25,Ilfov,15601,17490,19363,21001,23356,25515,26642,29132,32168,...,430805,444241,460486,473422,485307,486869,503675,545407,564833,583663
26,Maramures,9307,9938,10106,10355,10978,11304,11657,12492,13203,...,470714,468333,465423,463306,460756,458927,455160,451499,451728,451881
27,Mehedinti,3278,3314,3260,3261,3403,3489,3589,3841,3945,...,256011,252600,249336,244960,241153,238830,236362,233636,231398,230094
28,Mures,11838,12279,12486,13004,13630,14209,14711,15490,16062,...,546532,543726,540719,538214,535202,533355,529593,518991,519395,519831
29,Neamt,8181,8427,8491,8657,8847,9024,9197,9694,10132,...,459457,455643,451544,447232,442132,439179,433852,452057,449345,447776
30,Olt,6160,6342,6472,6622,6914,7236,7555,7870,8262,...,418463,412491,407717,400763,394448,389906,385935,381731,378567,376539
31,Prahova,15833,16260,16239,16621,17399,18292,19163,20166,21078,...,747634,740483,732847,725599,718098,712725,703580,694502,691246,688976
32,Salaj,4429,4644,4696,4894,5083,5347,5667,6004,6188,...,219039,217331,215878,213761,211663,209982,209114,211329,210652,210656
33,Satu Mare,6888,7226,7287,7488,7844,8019,8169,8639,8976,...,339987,338181,336543,334589,332610,331500,329535,330363,330662,330701
34,Sibiu,9909,10290,10399,10846,11412,11987,12642,13464,14286,...,400230,399982,399724,400018,400988,401352,400291,388896,391433,393581
35,Suceava,10231,10637,10938,11400,12211,12798,13142,14021,14958,...,631309,629733,628316,627439,625969,625431,622665,640816,642275,645196
36,Teleorman,4993,5051,4993,4993,5219,5309,5495,5798,6128,...,361615,355281,349628,341447,334217,329058,324405,322245,318043,315482
37,Timis,21275,22384,22667,23231,24387,25595,26356,27850,29249,...,695760,696720,698275,701506,705292,706585,706497,652238,658515,663543
38,Tulcea,4381,4523,4516,4665,4731,4882,4899,5259,5530,...,206013,203196,200706,197734,194439,192163,189747,192566,190994,189336
39,Valcea,6746,6960,7016,7211,7562,7880,8222,8744,9119,...,363270,359814,356647,353161,350089,348495,346039,341630,340914,340637
40,Vaslui,4437,4525,4635,4909,5248,5570,5666,6206,6480,...,390015,387525,383924,379987,374303,373127,369345,372861,371464,369517
41,Vrancea,5897,6108,6186,6311,6627,6932,7083,7531,7951,...,333808,330937,328057,324437,320722,317778,314494,334066,333154,332313

In [93]:
# Calculate the number of enterprises per 1,000 inhabitants for each county and year
df_enterprises_capita_2013_2024 = df_enterprises_capita.iloc[:, 1:13].values / df_enterprises_capita.iloc[:, 13:].values * 1000

# Convert the result into a DataFrame and clean the year column names
df_enterprises_capita_2013_2024 = pd.DataFrame(df_enterprises_capita_2013_2024, columns = df_enterprises_capita.columns[1:13].str.lstrip('E_'))

# Add the 'County' column as the first column
df_enterprises_capita_2013_2024.insert(0, 'County', df_enterprises_capita['County'].values)

# Display the resulting DataFrame
df_enterprises_capita_2013_2024

,County,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Alba,21.562985,22.394490,23.011774,23.757976,24.659016,26.003461,27.989861,30.070571,31.821394,31.978877,33.746831,34.013209
1,Arad,24.465522,25.630783,26.017720,26.844308,28.434379,29.937848,31.121038,32.622129,34.314283,35.258676,36.830218,37.065162
2,Arges,21.987874,23.239146,24.012954,25.140828,27.206438,28.891283,30.196377,32.138554,33.857473,34.684334,36.682475,37.085560
3,Bacau,17.340822,18.007331,18.090633,18.574671,19.626083,20.470245,20.992301,22.571868,23.612626,23.782395,24.701090,25.395712
4,Bihor,28.337998,30.256079,30.458503,31.625625,33.373295,34.771373,35.292484,37.196377,39.011466,40.782130,43.119693,43.971027
5,Bistrita-Nasaud,20.775711,21.566694,21.962543,22.998637,24.791479,26.612345,27.833957,30.816486,32.233100,31.403313,32.616330,33.317401
6,Botosani,9.285556,9.754343,10.048263,10.262908,11.088338,11.545210,12.050760,13.371143,14.009790,13.806928,14.899375,15.320156
7,Braila,19.334723,19.881340,20.100388,20.299202,21.221250,22.193358,23.030110,24.260456,25.555920,25.607075,26.268767,26.413007
8,Brasov,31.404743,32.511544,32.994049,33.989552,35.950246,37.548192,38.892811,41.087409,42.993317,44.802227,47.502501,48.297612
9,Bucharest Municipality,55.038181,58.461708,59.048746,60.156337,62.399163,63.756890,63.221232,65.070405,68.022907,74.070183,77.889071,79.500100
10,Buzau,19.445250,20.278176,20.596685,21.414568,22.590538,23.278414,24.049801,25.354920,26.637817,26.791839,28.184510,28.267025
11,Calarasi,14.199637,14.502565,15.098925,15.485356,16.124791,17.253290,17.908317,19.070675,20.103918,19.895028,21.182452,21.474929
12,Caras-Severin,15.719112,16.431901,16.386856,16.426698,17.168059,17.731902,17.926958,18.872540,19.355420,21.224510,22.425114,22.434701
13,Cluj,36.382171,38.840104,40.123712,42.429462,45.573295,48.404883,49.492752,51.530417,54.449079,58.832142,61.603208,63.438437
14,Constanta,29.635127,30.415318,30.269460,30.586415,32.184115,33.436130,34.569968,36.323836,38.021693,39.351114,41.664701,42.160327
15,Covasna,18.073846,18.175892,17.690503,18.363479,19.499436,20.420600,21.418711,22.416540,22.935482,23.285246,24.525138,24.374609
16,Dambovita,12.518836,13.121635,13.629620,14.364068,15.606391,16.726688,18.110662,19.594285,20.881306,21.911872,23.237782,23.714677
17,Dolj,20.475020,21.480806,21.672698,22.192063,23.265986,24.141636,25.374710,27.181635,28.375764,29.350545,31.927969,32.180704
18,Galati,20.671898,21.377618,21.831307,22.707083,23.545645,24.491793,24.941962,26.319448,27.252665,27.497323,28.825767,29.060321
19,Giurgiu,14.319708,15.426989,16.084492,16.290928,17.299965,18.344296,19.999474,22.166188,24.334665,24.511631,26.148691,26.354959
20,Gorj,17.139720,17.682597,17.898307,18.578054,20.161664,21.206428,22.896408,24.558143,26.122505,26.451561,27.876557,29.068942
21,Harghita,22.857272,23.485630,23.012749,23.270635,24.022167,24.666441,25.816184,26.462502,27.322898,28.364417,29.933861,30.166217
22,Hunedoara,20.619107,21.458228,21.449043,21.797218,22.716291,23.663584,24.745497,26.333010,27.801378,29.324188,30.794573,31.390981
23,Ialomita,14.441206,14.919112,15.219100,15.808381,16.424074,17.480696,18.378239,19.264249,20.384988,20.854379,21.556762,21.623009
24,Iasi,18.313520,18.986491,19.196561,20.059367,21.673935,23.013490,23.689264,25.934018,27.556324,30.248655,32.341333,33.126190
25,Ilfov,38.345356,41.857126,44.946089,47.273890,50.720326,53.894834,54.897209,59.835397,63.866581,63.088666,66.212491,67.814818
26,Maramures,19.630258,21.033561,21.469512,22.110336,23.587145,24.398562,25.299725,27.220015,29.007382,30.201617,31.873163,32.597078
27,Mehedinti,12.527229,12.794082,12.733828,12.909739,13.648250,14.243142,14.882668,16.082569,16.690500,17.356058,18.803101,20.087443
28,Mures,21.559032,22.412619,22.845872,23.916458,25.207178,26.400279,27.486818,29.042570,30.328951,31.524631,33.277178,33.966808
29,Neamt,17.602709,18.235957,18.480511,18.999524,19.592775,20.177447,20.801480,22.073004,23.353586,22.890919,24.244178,24.686450
30,Olt,14.387145,14.977152,15.466122,16.053684,16.957841,18.055559,19.153348,20.184352,21.407750,21.740440,22.849324,23.081274
31,Prahova,20.925545,21.610702,21.720521,22.446160,23.741654,25.209517,26.685773,28.294223,29.958214,31.094223,32.441417,33.056304
32,Salaj,19.978799,21.063231,21.439104,22.518647,23.545706,25.013917,26.773692,28.592927,29.591515,29.489564,30.666692,31.212023
33,Satu Mare,20.133404,21.184776,21.433172,22.141989,23.307571,23.966717,24.560296,26.060332,27.238381,27.509134,29.044765,29.582614
34,Sibiu,24.756408,25.707776,25.982560,27.116220,28.549699,29.966152,31.527128,33.546612,35.689036,38.151588,40.696620,41.503528
35,Suceava,16.182914,16.837090,17.325905,18.102910,19.434488,20.397202,20.994650,22.418140,24.022548,24.468802,25.943716,26.742261
36,Teleorman,13.414723,13.753986,13.807502,14.053665,14.927294,15.548533,16.441414,17.619994,18.889968,19.525516,20.648151,21.135913
37,Timis,30.799276,32.287518,32.578763,33.343380,34.924636,36.485789,37.368920,39.414932,41.400034,46.294451,48.718708,49.125678
38,Tulcea,20.850090,21.715021,21.920947,22.958129,23.571792,24.689735,25.195563,27.367391,29.144071,28.488934,30.184194,30.564710
39,Valcea,18.360409,19.032150,19.313458,20.040910,21.203038,22.312770,23.485457,25.090747,26.352521,27.553201,28.787319,29.136588
40,Vaslui,11.365645,11.606344,11.884158,12.667570,13.669372,14.658396,15.137469,16.632407,17.544572,17.835065,18.809360,18.586425
41,Vrancea,17.484404,18.192757,18.531611,19.070095,20.200758,21.366244,22.084547,23.698934,25.281881,24.174864,25.201558,25.301448

In [ ]:
# Transform the DataFrame from wide format to panel format
df_enterprises_capita_panel = df_enterprises_capita_2013_2024.melt( id_vars = 'County', var_name = 'Years', value_name = 'Enterprises per capita')

# Display the resulting panel DataFrame
df_enterprises_capita_panel

      County Years  Enterprises per capita
0       Alba  2013               21.562985
1       Arad  2013               24.465522
2      Arges  2013               21.987874
3      Bacau  2013               17.340822
4      Bihor  2013               28.337998
..       ...   ...                     ...
499    Timis  2024               49.125678
500   Tulcea  2024               30.564710
501   Valcea  2024               29.136588
502   Vaslui  2024               18.586425
503  Vrancea  2024               25.301448

[504 rows x 3 columns]

In [ ]:
# Export the panel DataFrame to an Excel file without including the index
df_enterprises_capita_panel.to_excel('enterprises_capita_county_2013_2024.xlsx', index = False)

## Demographic Dependency Index Processing

In [2]:
# Import the CSV file containing population data
# Rename the columns of the dataset
# Skip the first row from the file (original header)
df_pop = pd.read_csv('Data/Population/exportPivot_POP105A_2.csv', delimiter =',', names = ['Age', 'Sex', 'Areas', 'County', 'Years', 'Persons', 'Population'], skiprows = 1)

# Display the resulting DataFrame
df_pop

,Age,Sex,Areas,County,Years,Persons,Population
0,0- 4 years,Total,Total,Bihor,Year 2013,Number of persons,30148
1,0- 4 years,Total,Total,Bihor,Year 2014,Number of persons,29248
2,0- 4 years,Total,Total,Bihor,Year 2015,Number of persons,28702
3,0- 4 years,Total,Total,Bihor,Year 2016,Number of persons,28365
4,0- 4 years,Total,Total,Bihor,Year 2017,Number of persons,28656
...,...,...,...,...,...,...,...
9067,85 years and over,Total,Total,Timis,Year 2020,Number of persons,10698
9068,85 years and over,Total,Total,Timis,Year 2021,Number of persons,10899
9069,85 years and over,Total,Total,Timis,Year 2022,Number of persons,9577
9070,85 years and over,Total,Total,Timis,Year 2023,Number of persons,9873
9071,85 years and over,Total,Total,Timis,Year 2024,Number of persons,10545

In [3]:
# Remove unnecessary columns from the DataFrame
df_pop = df_pop.drop(['Sex', 'Areas', 'Persons'], axis = 1)

In [4]:
# Remove the 'Year' prefix from the values in the 'Years' column
df_pop['Years'] = df_pop['Years'].str.lstrip('Year ')

# Display the updated DataFrame
df_pop

                    Age  County Years  Population
0            0- 4 years   Bihor  2013       30148
1            0- 4 years   Bihor  2014       29248
2            0- 4 years   Bihor  2015       28702
3            0- 4 years   Bihor  2016       28365
4            0- 4 years   Bihor  2017       28656
...                 ...     ...   ...         ...
9067  85 years and over   Timis  2020       10698
9068  85 years and over   Timis  2021       10899
9069  85 years and over   Timis  2022        9577
9070  85 years and over   Timis  2023        9873
9071  85 years and over   Timis  2024       10545

[9072 rows x 4 columns]

In [5]:
# Remove leading spaces from the values in the 'County' column
df_pop['County'] = df_pop['County'].str.lstrip(' ')

In [6]:
df_pop

                    Age County Years  Population
0            0- 4 years  Bihor  2013       30148
1            0- 4 years  Bihor  2014       29248
2            0- 4 years  Bihor  2015       28702
3            0- 4 years  Bihor  2016       28365
4            0- 4 years  Bihor  2017       28656
...                 ...    ...   ...         ...
9067  85 years and over  Timis  2020       10698
9068  85 years and over  Timis  2021       10899
9069  85 years and over  Timis  2022        9577
9070  85 years and over  Timis  2023        9873
9071  85 years and over  Timis  2024       10545

[9072 rows x 4 columns]

In [7]:
# Define cateogories
young = ['0- 4 years', '5- 9 years', '10-14 years']

In [8]:
working = [
    '15-19 years', '20-24 years', '25-29 years',
    '30-34 years', '35-39 years', '40-44 years',
    '45-49 years', '50-54 years', '55-59 years',
    '60-64 years']

In [9]:
old = [
    '65-69 years', '70-74 years', '75-79 years',
    '80-84 years', '85 years and over']

In [10]:
# Create demographic category
def classify_age(age):
    if age in young:
        return 'young'
    elif age in working:
        return 'working'
    elif age in old:
        return 'old'
    else:
        return None

# Apply the classification function to the 'Age' column and create a new column
df_pop['Category'] = df_pop['Age'].apply(classify_age)

In [11]:
# Create a pivot table with population values grouped by county, year, and demographic category
df_pivot_pop = df_pop.pivot_table(values = 'Population', index = ['County', 'Years'], columns = 'Category', aggfunc = 'sum').reset_index()

In [12]:
# Dependency index calculation 
df_pivot_pop['Dependency index'] = ((df_pivot_pop['young'] + df_pivot_pop ['old']) / df_pivot_pop['working']) * 100

In [13]:
df_pivot_pop

Category   County Years    old  working  young  Dependency index
0            Alba  2013  59182   228883  51452         48.336486
1            Alba  2014  59800   227367  50550         48.533868
2            Alba  2015  60811   225187  49917         49.171577
3            Alba  2016  61760   222312  49416         50.008996
4            Alba  2017  63071   218788  49095         51.266980
..            ...   ...    ...      ...    ...               ...
499       Vrancea  2020  66862   198330  52586         60.226895
500       Vrancea  2021  67629   194935  51930         61.332752
501       Vrancea  2022  67205   211254  55607         58.134757
502       Vrancea  2023  67829   210322  55003         58.401879
503       Vrancea  2024  68810   209982  53521         58.257851

[504 rows x 6 columns]

In [15]:
# Export the dependency index DataFrame to an Excel file without including the index
df_pivot_pop.to_excel('dependency_index_county_2013_2024.xlsx', columns = ['County', 'Years', 'Dependency index'], index = False)

## Civil employment processing

In [117]:
# Import the CSV file containing civil employment data
# Rename the columns of the dataset
# Skip the first row from the file (original header)
df_pop_employed = pd.read_csv('Data/Civil employment/exportPivot_FOM103D.csv', delimiter =',', names = ['NACE', 'Sex', 'County', 'Years', 'Persons', 'Employed Population'], skiprows = 1)

# Display the resulting DataFrame
df_pop_employed

,NACE,Sex,County,Years,Persons,Employed Population
0,TOTAL,Total,Bihor,Year 2013,Thousands persons,266.4
1,TOTAL,Total,Bihor,Year 2014,Thousands persons,264.8
2,TOTAL,Total,Bihor,Year 2015,Thousands persons,262.8
3,TOTAL,Total,Bihor,Year 2016,Thousands persons,259.6
4,TOTAL,Total,Bihor,Year 2017,Thousands persons,260.4
...,...,...,...,...,...,...
499,TOTAL,Total,Timis,Year 2020,Thousands persons,346.7
500,TOTAL,Total,Timis,Year 2021,Thousands persons,324.6
501,TOTAL,Total,Timis,Year 2022,Thousands persons,333.7
502,TOTAL,Total,Timis,Year 2023,Thousands persons,331.9
503,TOTAL,Total,Timis,Year 2024,Thousands persons,332.5

In [118]:
# Remove unnecessary columns from the DataFrame
df_pop_employed = df_pop_employed.drop(['NACE', 'Sex', 'Persons'], axis = 1)

# Display the cleaned DataFrame
df_pop_employed

     County       Years  Employed Population
0     Bihor   Year 2013                266.4
1     Bihor   Year 2014                264.8
2     Bihor   Year 2015                262.8
3     Bihor   Year 2016                259.6
4     Bihor   Year 2017                260.4
..      ...         ...                  ...
499   Timis   Year 2020                346.7
500   Timis   Year 2021                324.6
501   Timis   Year 2022                333.7
502   Timis   Year 2023                331.9
503   Timis   Year 2024                332.5

[504 rows x 3 columns]

In [119]:
# Remove the 'Year' prefix from the values in the 'Years' column
df_pop_employed['Years'] = df_pop_employed['Years'].str.lstrip('Year ')

In [120]:
# Remove leading spaces from the values in the 'County' column
df_pop_employed['County'] = df_pop_employed['County'].str.lstrip(' ')

# Display the cleaned DataFrame
df_pop_employed

    County Years  Employed Population
0    Bihor  2013                266.4
1    Bihor  2014                264.8
2    Bihor  2015                262.8
3    Bihor  2016                259.6
4    Bihor  2017                260.4
..     ...   ...                  ...
499  Timis  2020                346.7
500  Timis  2021                324.6
501  Timis  2022                333.7
502  Timis  2023                331.9
503  Timis  2024                332.5

[504 rows x 3 columns]

In [121]:
# Merge the demographic and employment DataFrames based on county and year
df_pop_employed_2013_2024 = pd.merge(df_pivot_pop, df_pop_employed, on = ['County', 'Years'], how = 'inner')

# Display the merged DataFrame
df_pop_employed_2013_2024

,County,Years,old,working,young,Dependency_index,Employed Population
0,Alba,2013,59182,228883,51452,48.336486,163.3
1,Alba,2014,59800,227367,50550,48.533868,159.6
2,Alba,2015,60811,225187,49917,49.171577,159.2
3,Alba,2016,61760,222312,49416,50.008996,159.9
4,Alba,2017,63071,218788,49095,51.266980,162.1
...,...,...,...,...,...,...,...
499,Vrancea,2020,66862,198330,52586,60.226895,130.7
500,Vrancea,2021,67629,194935,51930,61.332752,108.0
501,Vrancea,2022,67205,211254,55607,58.134757,110.9
502,Vrancea,2023,67829,210322,55003,58.401879,109.2
503,Vrancea,2024,68810,209982,53521,58.257851,107.0

In [122]:
# Calculate the occupancy rate based on the employed and working-age population
df_pop_employed_2013_2024['Occupancy rate'] = (df_pop_employed_2013_2024['Employed Population'] * 1000 / df_pop_employed_2013_2024['working'] * 100)

In [123]:
df_pop_employed_2013_2024

,County,Years,old,working,young,Dependency_index,Employed Population,Occupancy rate
0,Alba,2013,59182,228883,51452,48.336486,163.3,71.346496
1,Alba,2014,59800,227367,50550,48.533868,159.6,70.194883
2,Alba,2015,60811,225187,49917,49.171577,159.2,70.696799
3,Alba,2016,61760,222312,49416,50.008996,159.9,71.925942
4,Alba,2017,63071,218788,49095,51.266980,162.1,74.089987
...,...,...,...,...,...,...,...,...
499,Vrancea,2020,66862,198330,52586,60.226895,130.7,65.900267
500,Vrancea,2021,67629,194935,51930,61.332752,108.0,55.403083
501,Vrancea,2022,67205,211254,55607,58.134757,110.9,52.496047
502,Vrancea,2023,67829,210322,55003,58.401879,109.2,51.920389
503,Vrancea,2024,68810,209982,53521,58.257851,107.0,50.956749

In [124]:
# Export the occupancy rate DataFrame to an Excel file without including the index
df_pop_employed_2013_2024.to_excel('occupancy_rate_county_2013_2024.xlsx', index = False, columns = ['County', 'Years', 'Occupancy rate'])

## Salary processing

In [3]:
# Import the CSV file containing salary data
# Rename the columns of the dataset
# Skip the first row from the file (original header)
df_salaries = pd.read_csv('Data/Salary/exportPivot_FOM106E.csv', names = ['NACE', 'Sex', 'County', 'Years', 'RON', 'Salary'], skiprows = 1)

# Display the resulting DataFram
df_salaries

      NACE     Sex  County       Years   RON  Salary
0    TOTAL   Total   Bihor   Year 2013   Lei    1155
1    TOTAL   Total   Bihor   Year 2014   Lei    1299
2    TOTAL   Total   Bihor   Year 2015   Lei    1396
3    TOTAL   Total   Bihor   Year 2016   Lei    1563
4    TOTAL   Total   Bihor   Year 2017   Lei    1871
..     ...     ...     ...         ...   ...     ...
499  TOTAL   Total   Timis   Year 2020   Lei    3536
500  TOTAL   Total   Timis   Year 2021   Lei    3845
501  TOTAL   Total   Timis   Year 2022   Lei    4251
502  TOTAL   Total   Timis   Year 2023   Lei    4910
503  TOTAL   Total   Timis   Year 2024   Lei    5508

[504 rows x 6 columns]

In [4]:
# Remove unnecessary columns from the DataFrame
df_salaries = df_salaries.drop(['NACE', 'Sex', 'RON'], axis = 1)

# Display the cleaned DataFrame
df_salaries

     County       Years  Salary
0     Bihor   Year 2013    1155
1     Bihor   Year 2014    1299
2     Bihor   Year 2015    1396
3     Bihor   Year 2016    1563
4     Bihor   Year 2017    1871
..      ...         ...     ...
499   Timis   Year 2020    3536
500   Timis   Year 2021    3845
501   Timis   Year 2022    4251
502   Timis   Year 2023    4910
503   Timis   Year 2024    5508

[504 rows x 3 columns]

In [5]:
# Remove the 'Year' prefix from the values in the 'Years' column
df_salaries['Years'] = df_salaries['Years'].str.lstrip('Year ')

In [6]:
# Remove leading spaces from the values in the 'County' column
df_salaries['County'] = df_salaries['County'].str.lstrip(' ')

# Display the updated DataFrame
df_salaries

    County Years  Salary
0    Bihor  2013    1155
1    Bihor  2014    1299
2    Bihor  2015    1396
3    Bihor  2016    1563
4    Bihor  2017    1871
..     ...   ...     ...
499  Timis  2020    3536
500  Timis  2021    3845
501  Timis  2022    4251
502  Timis  2023    4910
503  Timis  2024    5508

[504 rows x 3 columns]

In [7]:
# Import the Excel file containing inflation data
df_inflation = pd.read_excel('Data/Salary/inflation_ins.xlsx')

# Display the resulting DataFrame
df_inflation

    Years     IPC  Inflation_rate
0    2013  103.98             4.0
1    2014  101.07             1.1
2    2015   99.41            -0.6
3    2016   98.45            -1.5
4    2017  101.34             1.3
5    2018  104.63             4.6
6    2019  103.83             3.8
7    2020  102.63             2.6
8    2021  105.05             5.1
9    2022  113.80            13.8
10   2023  110.40            10.4
11   2024  105.59             5.6

In [8]:
# Sort the inflation data by year and reset the index
df_inflation = df_inflation.sort_values("Years").reset_index(drop=True)

# Create a cumulative price index with 2013 as the base year
# The value 100 means that prices in 2013 are treated as the reference level
df_inflation["Price_Index_2013_100"] = 100.0

# Calculate the cumulative price index for each year
# Each year's index is obtained by multiplying the previous year's index
# by the Consumer Price Index (IPC) of the current year
for i in range(1, len(df_inflation)):
    df_inflation.loc[i, "Price_Index_2013_100"] = (
        df_inflation.loc[i-1, "Price_Index_2013_100"] *
        df_inflation.loc[i, "IPC"] / 100
    )

# Extract the cumulative price index value for 2024
# This will be used as the new reference value
base_2024 = df_inflation.loc[
    df_inflation["Years"] == 2024,
    "Price_Index_2013_100"
].iloc[0]

# Rebase the price index so that 2024 becomes the reference year
# A value below 100 means that prices were lower than in 2024
df_inflation["Price_Index_2024_100"] = (
    df_inflation["Price_Index_2013_100"] /
    base_2024
) * 100

# Display the DataFrame
df_inflation

    Years     IPC  Inflation_rate  Price_Index_2013_100  Price_Index_2024_100
0    2013  103.98             4.0            100.000000             64.204793
1    2014  101.07             1.1            101.070000             64.891784
2    2015   99.41            -0.6            100.473687             64.508923
3    2016   98.45            -1.5             98.916345             63.509034
4    2017  101.34             1.3            100.241824             64.360055
5    2018  104.63             4.6            104.883020             67.339926
6    2019  103.83             3.8            108.900040             69.919045
7    2020  102.63             2.6            111.764111             71.757916
8    2021  105.05             5.1            117.408199             75.381691
9    2022  113.80            13.8            133.610530             85.784364
10   2023  110.40            10.4            147.506025             94.705938
11   2024  105.59             5.6            155.751612            100.000000

In [9]:
# Convert the values in the 'Years' column to string type
df_inflation['Years'] = df_inflation['Years'].astype(str)

In [10]:
# Merge the salary and inflation DataFrames based on the 'Years' column
df_real_salary = pd.merge(df_salaries, df_inflation, on = "Years", how="inner")

# Display the merged DataFrame
df_real_salary

,County,Years,Salary,IPC,Inflation_rate,Price_Index_2013_100,Price_Index_2024_100
0,Bihor,2013,1155,103.98,4.0,100.000000,64.204793
1,Bihor,2014,1299,101.07,1.1,101.070000,64.891784
2,Bihor,2015,1396,99.41,-0.6,100.473687,64.508923
3,Bihor,2016,1563,98.45,-1.5,98.916345,63.509034
4,Bihor,2017,1871,101.34,1.3,100.241824,64.360055
...,...,...,...,...,...,...,...
499,Timis,2020,3536,102.63,2.6,111.764111,71.757916
500,Timis,2021,3845,105.05,5.1,117.408199,75.381691
501,Timis,2022,4251,113.80,13.8,133.610530,85.784364
502,Timis,2023,4910,110.40,10.4,147.506025,94.705938
503,Timis,2024,5508,105.59,5.6,155.751612,100.000000

In [11]:
# Calculate the real salary adjusted for inflation using 2024 as the reference year
df_real_salary['Real salary'] = (df_real_salary['Salary'] / df_real_salary['Price_Index_2024_100']) * 100

In [12]:
# Display the first 12 rows of the DataFrame
df_real_salary.head(12)

,County,Years,Salary,IPC,Inflation_rate,Price_Index_2013_100,Price_Index_2024_100,Real salary
0,Bihor,2013,1155,103.98,4.0,100.000000,64.204793,1798.931119
1,Bihor,2014,1299,101.07,1.1,101.070000,64.891784,2001.794242
2,Bihor,2015,1396,99.41,-0.6,100.473687,64.508923,2164.041719
3,Bihor,2016,1563,98.45,-1.5,98.916345,63.509034,2461.067177
4,Bihor,2017,1871,101.34,1.3,100.241824,64.360055,2907.082641
5,Bihor,2018,2087,104.63,4.6,104.883020,67.339926,3099.201503
6,Bihor,2019,2385,103.83,3.8,108.900040,69.919045,3411.087770
7,Bihor,2020,2603,102.63,2.6,111.764111,71.757916,3627.474350
8,Bihor,2021,2766,105.05,5.1,117.408199,75.381691,3669.326024
9,Bihor,2022,3099,113.80,13.8,133.610530,85.784364,3612.546446
10,Bihor,2023,3609,110.40,10.4,147.506025,94.705938,3810.743100
11,Bihor,2024,4095,105.59,5.6,155.751612,100.000000,4095.000000

In [14]:
# Export the real salary DataFrame to an Excel file without including the index
# Save salary values without decimal places
df_real_salary.to_excel('real_salary_county_2013_2024.xlsx', index = False, columns = ['County', 'Years', 'Real salary'], float_format = '%.0f')